<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtLogin</name>
   <tag></tag>
   <elementGuidId>d64a9077-5179-4ef3-8b49-5c09f3cf76e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toolbar-1009-innerCt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toolbar-1009-innerCt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6cb34df1-695a-4459-95f3-b7226717002c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toolbar-1009-innerCt</value>
      <webElementGuid>ee9523f6-a60f-4695-bb8e-c0e2ed29be7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>innerCt</value>
      <webElementGuid>05b65156-cd51-48e7-b680-56dedb7d56bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e6c3dd38-9d8b-4776-a4cd-4d3b4eca46a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner</value>
      <webElementGuid>0436f3d4-94f9-4488-8faf-df80799eb742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>385c9c82-cf8e-479c-9a89-11417c0519a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toolbar-1009-innerCt&quot;)</value>
      <webElementGuid>0165afe3-d983-4d60-b56c-499953fe03e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toolbar-1009-innerCt']</value>
      <webElementGuid>3e39ebd4-952f-411f-bb44-82a57cdb8a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toolbar-1009']/div</value>
      <webElementGuid>76bbc5b6-4571-417b-82af-7e44d581f259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='txtIvAes:'])[1]/following::div[25]</value>
      <webElementGuid>8ba1cd2b-d404-4ebf-8e19-ce96dc94998a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='txtKeyAes:'])[1]/following::div[31]</value>
      <webElementGuid>37656500-e23c-406f-b4c0-f67943148638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[1]/preceding::div[2]</value>
      <webElementGuid>040a6da2-f342-440a-8363-2643f2a4501d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>1f5122f3-6e69-4fd0-8982-24b44adb5d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toolbar-1009-innerCt' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>0f04bc63-011f-4947-bc5b-4bba62a7bf20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
